export const mainNavItems = [
  { label: "Dashboard", path: "/dashboard", icon: "dashboard" },
  { label: "Categories", path: "/categories", icon: "categories" },
  { label: "Courses", path: "/courses", icon: "courses" },
  { label: "Lessons", path: "/lessons", icon: "lessons" },
  { label: "Videos", path: "/videos", icon: "videos" },
  { label: "Test Management", path: "/questions", icon: "questions" },
  { label: "Online Test", path: "/questions/test", icon: "test" },
  { label: "Instructors", path: "/instructors", icon: "instructors" },
  { label: "Students", path: "/students", icon: "students" },
  { label: "Orders", path: "/orders", icon: "orders" },
  { label: "Coupons", path: "/coupons", icon: "coupons" },
  { label: "Reviews", path: "/reviews", icon: "reviews" },
  { label: "Payouts", path: "/payouts", icon: "payouts" },
  { label: "Withdrawals", path: "/withdrawals", icon: "withdrawals" },
  { label: "Reports", path: "/reports", icon: "reports" },
  { label: "Settings", path: "/settings", icon: "settings" },
];

export const systemNavItems = [
  { label: "Users", path: "/users", icon: "users" },
  { label: "Roles & Permissions", path: "/roles", icon: "roles" },
  { label: "Announcements", path: "/announcements", icon: "announcements" },
  { label: "Site Settings", path: "/site-settings", icon: "siteSettings" },
  { label: "Support Tickets", path: "/support", icon: "support" },
  { label: "Activity Logs", path: "/activity-logs", icon: "activity" },
];

export const pageTitles = {
  "/dashboard": "Dashboard",
  "/courses": "Courses",
  "/courses/upload": "Course Upload",
  "/courses/:courseId/curriculum": "Course Curriculum",
  "/lessons": "Lessons",
  "/videos": "Upload Video",
  "/questions": "Test Management",
  "/questions/list": "Question Management",
  "/questions/test": "Online Test",
  "/questions/test/result": "Test Result",
  "/questions/:id": "Question Details",
  "/categories": "Categories",
  "/instructors": "Instructors",
  "/students": "Students",
  "/orders": "Orders",
  "/coupons": "Coupons",
  "/reviews": "Reviews",
  "/payouts": "Payouts",
  "/withdrawals": "Withdrawals",
  "/reports": "Reports",
  "/settings": "Settings",
  "/users": "Users",
  "/roles": "Roles & Permissions",
  "/announcements": "Announcements",
  "/site-settings": "Site Settings",
  "/support": "Support Tickets",
  "/activity-logs": "Activity Logs",
};
